version: "3.7"
services:
        beacon:
                container_name: beacon-chain
                image: gcr.io/prysmaticlabs/prysm/beacon-chain:${IMAGE_VERSION_TAG}
                restart: always
                hostname: beacon-chain
                command: --datadir=/data --p2p-host-ip=${PUBLIC_IP} --enable-new-state-mgmt
                ports:
                        - 13000:13000
                        - 12000:12000
                volumes:
                        - ./beacon:/data
                logging:
                        driver: "json-file"
                        options:
                                max-file: "10"
                                max-size: "100m"
        validator:
                container_name: validator
                image: gcr.io/prysmaticlabs/prysm/validator:${IMAGE_VERSION_TAG}
                restart: on-failure
                hostname: validator
                command: --beacon-rpc-provider=beacon:4000 --keymanager=keystore --keymanageropts=/data/keystore.json
                volumes:
                        - ./validator:/data
                logging:
                        driver: "json-file"
                        options:
                                max-file: "10"
                                max-size: "100m"
        slasher:
                container_name: slasher
                image: gcr.io/prysmaticlabs/prysm/slasher:${IMAGE_VERSION_TAG}
                restart: always
                hostname: slasher
                command: --beacon-rpc-provider=beacon:4000 --datadir=/data
                volumes:
                        - ./slasher:/data
                logging:
                        driver: "json-file"
                        options:
                                max-file: "10"
                                max-size: "100m"
