version: "3.7"
services:
        geth:
                image: tianon/true
                restart: "no"
                command: ""
                entrypoint: ""
        beacon:
                volumes:
                        - ./config/beacon-no-geth.yaml:/config/beacon.yaml:ro
                        - ./beacon:/data
        slasher:
                image: tianon/true
                restart: "no"
                command: ""
                entrypoint: ""
        prometheus:
                image: tianon/true
                restart: "no"
                command: ""
                entrypoint: ""
        grafana:
                image: tianon/true
                restart: "no"
                command: ""
                entrypoint: ""

