############################################################
##
## Read up on parameters on
## https://docs.prylabs.network/docs/prysm-usage/parameters/
##
############################################################

datadir: /data

##############
# Connectivity
beacon-rpc-provider: beacon:4000

###############
# gRPC security
tls-cert: /config/tls/beacon.crt
